version: "3.8"
services:

  events:
    build: ./events/
    ports:
      - 8081:9001
    container_name: events
    environment:
      - PORT= 9001
    volumes:
      - "./events/:/app"
    networks:
      - my-network

  tickets:
    build: ./tickets/
    ports:
      - 8082:9002
    container_name: tickets
    environment:
      - PORT= 9002
    volumes:
      - "./tickets/:/app"

  consul:
    image: consul:latest
    container_name: consul
    command: "agent -dev -config-dir=/consul/config"
    ports:
      - "8500:8500"
    volumes:
      - ./events/events.hcl:/consul/config/events.hcl
    networks:
      - my-network

networks:
  my-network:
