apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: tickets-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata: 
      labels: 
        app: tickets
    spec:
      containers: 
        - name: tickets 
          image: terjenf/tickets:0.0.1
---
apiVersion: v1
kind: Service
metadata: 
  name: tickets-service
spec: 
  selector: 
    app: tickets
  ports: 
   - name: tickets 
     protocol: TCP 
     port: 9002
     targetPort: 9002
